#!/bin/bash
a=$1
if [ -z $1 ];then
	read -p "输入需要连接虚拟机的IP地址 " a
fi
	ping 192.168.4.$a -c 2   -W 1 -i 0.2 &>/dev/null
	if [ $? = 0 ];then
		ssh -X root@192.168.4.$a
	else
		virsh list --all
		read -p " 请先开机" b
		virsh start $b
		sleep 10
		while : 
		do
			ping 192.168.4.$a -c 2  -W 1  -i 0.2 &>/dev/null
			if [ $? -eq 0 ];then
				break
			fi
			sleep 1
		done
		ssh -X root@192.168.4.$a
	fi
